### PR TITLE
Added navigation functionality to docs

### PR DESCRIPTION
**Pull request by kritika-singh3**
This is WIP. Styling bit is not finalized yet. There are issues with the container alignments across various screen size. Asked @naveenbhaskar to help us out with the same.

### CODE REVIEW

**Comment by arvindsv** [comment]
@naveenbhaskar Can we get this done quickly? Currently, I consider navigation in the docs site to be broken.

/cc @maheshp

**Comment by streisguth** [comment]
What are the issues with container alignments? I had not noticed anything serious when reviewing the docs before they launched.

**Comment by arvindsv** [comment]
@streisguth If you go to a page like this:

https://docs.gocd.org/current/gocd_on_kubernetes/gocd_helm_chart/setup_and_configuration.html

... there's no indication of what to do next. Compare with the older version:

https://docs.gocd.org/19.1.0/gocd_on_kubernetes/gocd_helm_chart/setup_and_configuration.html

Not great. But, at least it has the next and previous buttons. With the change in this pull request, it looks like this:



You can see the "Previous Page" and the "Next page" links are not aligned properly. @kritika-singh3 has asked @naveenbhaskar to look at it, and I haven't seen any progress on it.

**Comment by kritika-singh3** [comment]
Screenshots:

1. Desktop
Screen Shot 2019-03-14 at 11 21 47 AM

2. Tablet
Screen Shot 2019-03-14 at 11 22 21 AM

3. Phone
Screen Shot 2019-03-14 at 11 22 31 AM

**Comment by bdpiparva** [comment]
@arvindsv @adityasood - I have backported this change in 19.2.0.

**Pull request merged**
