### PR TITLE
Backport sitemap

### PR DESCRIPTION
**Pull request by arvindsv**
Backport https://github.com/gocd/docs.go.cd/commit/55012608de5614de7eea915fc6556b3e0acf0a0f

Equivalent of: https://github.com/gocd/docs.go.cd/pull/108

### CODE REVIEW

**Comment by ketan** [comment]
We'll need a uber sitemap.xml at the top level too? That's templated everytime a new release is out.

**Comment by arvindsv** [comment]
Merging. /cc @varshavaradarajan

**Comment by arvindsv** [comment]
@ketan - Sorry, didn't see. I didn't do anything else, because my expectation is that only /current/sitemap.xml matters. Would you like every version to have the correct sitemap.xml? If so, I'll see what I can do to keep the version proper.

**Comment by arvindsv** [comment]
Matters = indexed by search engines, since robots.txt will disallow everything else.

**Comment by arvindsv** [comment]
I guess you're talking about: https://docs.gocd.org/sitemap.xml?

**Comment by ketan** [comment]
Because every release will have this commit from this point on, the sitemap will be generated for every release henceforth. My assumption is that just having /current/sitemap.xml won't be enough. We'd need to setup canonical urls. sitemap.xml just makes things easier to discover, which given the size of our website is not exactly a challenge for google.

**Comment by varshavaradarajan** [comment]
Then, why can't we have just one sitemap.xml at the top level in gh-pages? This will only whitelist the urls with current in it.

**Comment by ketan** [comment]
What we need is not a whitelist or a blacklist. Neither of these work as you'd expect them to work. For SEO to work effectively, we need a way for us to add canonical links.

**Comment by arvindsv** [comment]
I wonder if they are really canonical, though. I don't know if /current is really _the_ canonical version of a page for 17.3. That page is the canonical version for 17.3 and it can be different from the one for current. AFAIK, canonical is used when the _same_ content is shared under different locations. No?

**Comment by arvindsv** [comment]
About whitelist/blacklist, I think we've made the decision that only /current should be indexed by the search engines. So, trying to "blacklist" the older versions seems appropriate, as long as we don't link to them. In that sense, https://docs.gocd.org should have a rel=nofollow. Nothing else probably links directly to the /17.7, /17.8 pages. What am I missing?

**Comment by arvindsv** [comment]
I also considered adding a header to all the older pages, saying that the latest version (not canonical) is "/current". Not that it'll help SEO, if it's done in JS.

**Comment by varshavaradarajan** [comment]
@arvindsv - At this moment, every time a release is made, a sitemap.xml exists in https://docs.gocd.org/current, docs.gocd.org/17.8.0, docs.gocd.org/17.9.0 - and the sitemap.xml content is the same in all these directories. Its better to put it at the top level where robots.txt exists? https://github.com/gocd/docs.go.cd/tree/gh-pages

**Comment by arvindsv** [comment]
Yes, I don't mind putting it at the top-level. It needs to be recreated/updated every time, though.

**Comment by varshavaradarajan** [comment]
we can update it while bumping version every release, I think

**Pull request merged**
