### PR TITLE
Improve docs table of contents

### PR DESCRIPTION
**Pull request by arvindsv**
Paired with @ankitsri11.

* Make table-of-contents menu collapsible.
* Change introduction page to be a list of useful links.
* Change styling on navigation buttons.

### CODE REVIEW

**Comment by ankitsri11** [comment]
- Make table-of-contents menu collapsible.

table-of-contents

**Comment by arvindsv** [comment]
Introduction page looks like this:

<hr>

Screenshot_2019-06-12 Introduction GoCD User Documentation(1)

<hr>

**Comment by ankitsri11** [comment]
- Changed styling on navigation buttons.

navigation-buttons

**Comment by arvindsv** [comment]
@kritika-singh3 

> any reason for showing the navigation button on top as well as in the footer?

When someone reaches the end of a page, I felt that having buttons to go to the next page at the bottom makes it feel more natural. There are also some pages such as: https://docs.gocd.org/current/gocd_on_kubernetes/gocd_helm_chart/setup_and_configuration.html where it is not currently obvious what needs to happen next.

> The edit link in between the page width on the index page - that looks a little odd to me.

Do you mean in the introduction page? https://github.com/gocd/docs.go.cd/pull/319#issuecomment-501453713 ? If so, I can look into getting rid of it.

**Comment by arvindsv** [comment]
@kritika-singh3 I talked to Steven - and he suggested trying this navigation option for now, since we don't know how it's being used currently. I changed the text of the "Edit" link a bit, as well.

**Pull request merged**
