### PR TITLE
New images for Managing Agents and Managing Environments pages

### PR DESCRIPTION
**Pull request by anishvenkat**

### CODE REVIEW

**Comment by arvindsv** [comment]
@anishvenkat Looks good! Some thoughts:

- Can you see if the text in /configuration/managing_environments.html#add-a-new-agent-to-an-existing-environment makes sense any more? It talks about a forward slash, etc. which made sense in the older UI. Might be good to use an image which shows the different cases.

- Same here: /configuration/managing_a_build_cloud.html#associate-selected-agents-with-existing-resources

- You'll have to show disabled agents, like in the original image for [this](https://github.com/anishvenkat/docs.go.cd/blob/202c420dfc995320ca7039dcb45a5fb92868d735/resources/images/delete_agent.png).

- Just like in the other PR (#188), there are a lot of big images here. It's better to reduce their size (width, height, keeping aspect ratio the same) and then running optipng on it.

**Comment by anishvenkat** [comment]
@arvindsv: Thank you for your inputs. I have pushed the images after running optipng on them and also changed the images and documentation for the points that you have mentioned. Please review and let me know if you want me to make any other changes.

**Comment by arvindsv** [comment]
@anishvenkat Thanks! This looks good. Merging.

Can you take a look at resources/images/env_variables_environment.png and resources/images/env_variables_job.png? It looks like they are unchanged.

**Comment by anishvenkat** [comment]
@arvindsv - Sure. I was working on one page at a time. I've opened another PR - [195](https://github.com/gocd/docs.go.cd/pull/195) where I pushed the images for the same.

**Pull request merged**
