### PR TITLE
Upgrade Gitbook to 3.2.2

### PR DESCRIPTION
**Pull request by arvindsv**
We use a really old version of gitbook. 3.2.2 is the latest stable one. I haven't noticed too many changes, apart from:

1. Font looks a little different (Helvetica Neue instead of Open Sans)
2. Search is a little better (shows results on the right)
3. The "Edit this page" link shows and works now (if we want).
4. Numbers are missing from the table of contents. I'm of the opinion that they don't matter much and are all wrong currently, any way.
  image

Upgrading also allows us to add front-matter and use it in templates, to add meta keywords to the head tag of pages. That's my motive for this.

### CODE REVIEW

**Comment by ketan** [comment]
LGTM, the reason that the redirect was no longer a plugin is that we get the entire sidebar and layout and then the page redirects, adding page load time, but that is ok, I guess.

What about gitbook stuff in package.json?

Also, should we move to yarn, since it manages transitive department a lot better than npm?

**Comment by arvindsv** [comment]
The package.json has gitbook-cli only, which doesn't seem to matter much since we use it through npm/yarn run.

We're now using yarn. I've checked in the yarn.lock file and it works well for me. Only on Node 6, though. On Node 7, it complains about `internal/fs` as usual.

**Comment by arvindsv** [comment]
I'm checking to see whether I can upgrade gitbook-cli and others. Just a second.

**Comment by arvindsv** [comment]
Done. All packages in package.json are also upgraded. This now works with both Node 6 and 7 and uses yarn.

**Comment by arvindsv** [comment]
@varshavaradarajan - This still runs a Snap build.

**Comment by ketan** [comment]
Couple of things:

* You missed fixing `rakelib/build.rake`
* Remove the "hello" from the notification plugin page
* make similar change to dev docs too

Also, remember to backport, this will run forever, so run it and forget about it:

```bash
export GIT_SHA=....
git branch -a | grep upstream | grep release| sort --version-sort --reverse | cut -f3 -d/ | xargs -I VERSION bash -c "git reset --hard && git clean -fdx && git checkout && git branch -D VERSION && git checkout VERSION && git cherry-pick $GIT_SHA && git push && sleep 180; git branch -D VERSION"
```

**Comment by arvindsv** [comment]
Done. I'm planning to run a slightly changed version:

```
git branch -a | grep upstream | grep release| sort --version-sort --reverse | cut -f3 -d/ | xargs -I VERSION bash -c "git reset --hard && git clean -fdx && git checkout && (git branch -D VERSION; true) && git checkout -b VERSION upstream/VERSION && git cherry-pick $GIT_SHA && git push && sleep 300; git checkout master && git branch -D VERSION"
```

Also, this doesn't apply cleanly on 16.4, 16.5, 16.6. I'll do those later.

**Comment by arvindsv** [comment]
Dev docs are next, after this.

**Pull request merged**
