### PR TITLE
Backport SEO changes

### PR DESCRIPTION
**Pull request by arvindsv**
This is almost, just:
```
git merge --squash 9cff4eda4b094ba68f49989f28e907361de1a51d
```

with some small changes.

https://github.com/gocd/docs.go.cd/commit/9cff4eda4b094ba68f49989f28e907361de1a51d

### CODE REVIEW

**Comment by arvindsv** [comment]
@varshavaradarajan - Merging this.

**Comment by varshavaradarajan** [comment]
Looks fine. Want me to cherry pick to other release branches?

**Comment by arvindsv** [comment]
No. It's ok. Wanted to do this only because it is /current.

Thanks!

Looks fine. Want me to cherry pick to other release branches?

**Comment by varshavaradarajan** [comment]
Alright. Then, https://github.com/gocd/docs.go.cd/pull/107 is also for master and current branch.

**Pull request merged**
